
jeu:
    resource: "@JeuBundle/Resources/config/routing.yml"
    prefix:   /jeu

user:
    resource: "@LLUserBundle/Resources/config/routing.yml"
    prefix: /user

app:
    resource: '@AppBundle/Controller/'
    type: annotation

