<?php

namespace LL\JeuBundle\Repository;

/**
 * CartesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartesRepository extends \Doctrine\ORM\EntityRepository
{
}
