<?php

namespace LL\JeuBundle\Repository;
use LL\JeuBundle\Entity\Joueur;
use LL\JeuBundle\Entity\TableJeu;

/**
 * JoueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueurRepository extends \Doctrine\ORM\EntityRepository
{

    public function recupererListJoueur(TableJeu $table, Joueur $joueur){
        // On récupère les joueurs a la table
        $qb = $this->createQueryBuilder('j');

        $qb->where('j.id != :joueur')
            ->setParameter('joueur', $joueur->getId())
            ->andWhere('j.table = :table')
            ->setParameter('table', $table->getId())
        ;

        return $listJoueur = $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
