<?php

namespace LL\JeuBundle\Repository;

/**
 * tableJeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableJeuRepository extends \Doctrine\ORM\EntityRepository
{
}
