<?php

namespace LL\JeuBundle\Repository;

/**
 * tableJeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableJeuRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Retourne la premiere table non pleine
     * @return TableJeu
     */
    public function trouverPartie(){

        $max_Joueur = 4;

        $qb = $this->createQueryBuilder('t');

        $qb->where('t.nbJoueur < :maxJoueur')
            ->setParameter('maxJoueur', $max_Joueur);

        $listTable = $qb
            ->getQuery()
            ->getResult()
            ;

        //retourne la premiere table non pleine
        $table = current($listTable);
        return $table;
    }

}
