jeu_creerPartie:
    path:    /creationPartie
    defaults: { _controller: JeuBundle:Jeu:creerPartie }

jeu_partie:
    path:    /partie/{id}
    defaults: { _controller: JeuBundle:Jeu:afficherPartie }
    requirements:
        id: \d+

jeu_rejoindrePartie:
    path:    /rejoindrePartie/{id}
    defaults: { _controller: JeuBundle:Jeu:rejoindrePartie }
    requirements:
        id: \d+

jeu_accueil:
    path:    /accueil
    defaults: { _controller: JeuBundle:Affichage:accueil }


jeu_refreshPartie:
    path:    /refreshPartie
    defaults: { _controller: JeuBundle:Jeu:refreshPartie }
    methods: POST

jeu_lancerPartie:
    path: /lancerPartie/{id}
    defaults: { _controller: JeuBundle:Jeu:lancerPartie }
    requirements:
            id: \d+

jeu_jouer:
    path: /jouer/{id_table}/{id_carte}
    defaults: { _controller: JeuBundle:Jeu:jouerTour}
